## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('trace-replay-example',
				  ['point-to-point', 'wifi', 'internet', 'applications'])
    obj.source = 'trace-replay-example.cc'